name: Smoke tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  smoke-test:
    strategy:
      matrix:
        test:
          - default-config-macro
          - docker-registry
          - double_slash
          - forced-language
          - git-clone
          - git-push
          - gitweb
          - healthcheck
          - i18n
          - lightpanda
          - log-file
          - nginx
          - palemoon/amd64
          #- palemoon/i386
          - robots_txt
          - traefik
          - wildcard-match
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "24.15.0"
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "stable"
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          cache: false
          target: wasm32-unknown-unknown
      - name: Setup `wasmtime`
        uses: bytecodealliance/actions/wasmtime/setup@9152e710e9f7182e4c29ad218e4f335a7b203613 # v1.1.3

      - uses: ko-build/setup-ko@61b4d1d396f5b2e7d6bb6fefdce3dc38d1a13445 # v0.10

      - name: Install utils
        run: |
          go install ./utils/cmd/...

      - name: Run test
        run: |
          cd test/${{ matrix.test }}
          backoff-retry --try-count 10 ./test.sh

      - name: Sanitize artifact name
        if: always()
        run: echo "ARTIFACT_NAME=${{ matrix.test }}" | sed 's|/|-|g' >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: test/${{ matrix.test }}/var
